# Generated by Django 5.0.7 on 2024-08-08 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_alter_book_options_alter_book_table'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
            ],
        ),
    ]
